INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(44, 2, 46, 44, 2, 42, 42, 'breaking bread', 'Connection of Community Practices', 'Both passages emphasize the practice of ''breaking bread'' as a central activity among the early believers. This connection highlights the communal aspect of their faith, as they engaged in fellowship and shared meals together.', 'theme', 0.391, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 46, 19, 86, 11, 11, 'with one accord', 'Unity of Heart and Purpose', 'This connection highlights the theme of unity in both passages. Acts 2:46 speaks of being ''with one accord,'' while Psalms 86:11 expresses a desire for a united heart to fear the Lord.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 46, 47, 1, 12, 12, 'with gladness and singleness of heart', 'Joy and Sincerity in Community', 'This connection highlights the themes of gladness and simplicity in communal life. Both passages emphasize living with a sincere heart and rejoicing in fellowship.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 46, 51, 3, 22, 22, 'singleness of heart', 'Connection of Singleness of Heart', 'Both passages emphasize ''singleness of heart'' as a quality of devotion and sincerity in actions, whether in communal worship or in serving others. This connection highlights the importance of genuine commitment in both contexts.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 46, 45, 12, 8, 8, 'with gladness and singleness of heart', 'Unity and Generosity in Community', 'This connection highlights the themes of community and generosity. Both passages emphasize the importance of acting with gladness and simplicity in communal life.', 'theme', 0.34199999999999997, 'medium', 'v1.2', 'gpt-4o-mini'),
(44, 2, 46, 16, 8, 10, 10, 'with gladness and singleness of heart', 'Joy and Community in Worship', 'This connection highlights the themes of communal joy and shared meals in worship. Both passages emphasize the importance of gladness and celebration in the context of serving God and one another.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 44, 16, 5, 5, 'daily such as should be saved', 'Growth of the Early Church', 'Both passages emphasize the daily increase of the church. Acts 2:47 notes that the Lord added to the church daily, while Acts 16:5 states that the churches increased in number daily.', 'theme', 0.475, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 44, 5, 13, 14, 'added to the church daily', 'Growth of the Early Church', 'Both passages emphasize the addition of believers to the church. Acts 2:47 states that the Lord added to the church daily, while Acts 5:14 notes that believers were added to the Lord in multitudes.', 'theme', 0.419, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 46, 1, 18, 18, NULL, 'Connection of Salvation Themes', 'Both passages emphasize the concept of being ''saved.'' Acts 2:47 speaks of the Lord adding to the church those who should be saved, while 1 Corinthians 1:18 contrasts the saved with those who perish, highlighting the power of God in salvation.', 'theme', 0.391, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 45, 14, 18, 18, 'having favour with all the people', 'Connection of Acceptance and Favor', 'Both passages emphasize being acceptable to God and having favor with people. Acts 2:47 mentions having favor with all the people, while Romans 14:18 speaks of being approved of men.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 56, 3, 4, 5, 'such as should be saved', 'Salvation and God''s Mercy', 'Both passages emphasize the theme of salvation as a divine act. Acts 2:47 highlights that the Lord adds to the church those who are saved, while Titus 3:4-5 explains that salvation is according to God''s mercy, not by human works.', 'theme', 0.363, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 45, 8, 30, 30, 'added to the church daily such as should be saved', 'Salvation and Divine Calling', 'This connection highlights the theme of God actively adding to the community of believers, as seen in Acts, and the process of divine calling and justification in Romans. Both passages emphasize God''s initiative in the salvation of individuals.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini'),
(44, 2, 47, 42, 2, 52, 52, 'having favour with all the people', 'Favor with God and Man', 'Both passages emphasize the theme of gaining favor with God and people. In Acts, the church receives favor from all the people, while in Luke, Jesus increases in favor with God and man.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();
