INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 14, 28, 50, 2, 6, 11, 'my Father is greater than I', 'Humility and Exaltation of Christ', 'This connection highlights the theme of humility in Christ''s obedience and His subsequent exaltation. John 14:28 emphasizes Jesus'' submission to the Father, while Philippians 2:6-11 describes His humility and ultimate glorification by God.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 28, 58, 1, 2, 3, 'my Father is greater than I', 'Connection of Authority and Glory', 'This connection highlights the relationship between Jesus and the Father. Both passages emphasize the authority of the Father and the glory of the Son, with John noting the Father''s greatness and Hebrews describing the Son as the brightness of His glory.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 28, 58, 2, 9, 15, 'I go unto the Father', 'Connection of Suffering and Glory', 'This connection highlights the theme of Jesus'' suffering leading to glory. In John 14:28, Jesus speaks of going to the Father, while Hebrews 2:9-15 discusses Jesus'' suffering and subsequent glory as the captain of salvation.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 29, 43, 13, 19, 19, 'before it come to pass', 'Connection of Foretelling Belief', 'Both passages emphasize the act of telling beforehand to foster belief. They highlight the importance of prophecy in affirming Jesus'' identity.', 'theme', 0.363, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 29, 43, 16, 4, 31, 'that, when it is come to pass, ye might believe', 'Connection of Foretelling and Belief', 'Both passages emphasize the importance of foretelling events to strengthen belief. In John 14:29, Jesus states that he tells them things before they happen so they might believe, which is echoed in John 16:4, where he mentions telling them these things for remembrance.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 29, 40, 24, 24, 25, 'I have told you before', 'Forewarning of Deception', 'Both passages emphasize the importance of prior warning about future events. John 14:29 states that Jesus tells his followers beforehand to strengthen their belief, while Matthew 24:25 reiterates this by noting that he has also warned them about false prophets.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 62, 5, 19, 19, 'prince of this world', 'World and Wickedness Connection', 'Both passages emphasize the presence of evil in the world. John refers to the ''prince of this world,'' while 1 John states that ''the whole world lieth in wickedness.'' This connection highlights the pervasive nature of wickedness in the world.', 'theme', 0.524, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 62, 4, 4, 4, 'prince of this world cometh', 'Overcoming the Prince of the World', 'Both passages emphasize the conflict between believers and the ''prince of this world.'' John 14:30 mentions the prince''s approach, while 1 John 4:4 assures believers of their victory over him through God''s power.', 'theme', 0.46099999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 66, 12, 9, 9, 'prince of this world cometh', 'Connection of the Prince of Darkness', 'Both passages emphasize the presence of the Devil as a deceiver and adversary. John refers to the ''prince of this world,'' while Revelation describes the same figure as the ''great dragon'' and ''Devil.'' This connection highlights the ongoing conflict between Jesus and the forces of evil.', 'theme', 0.45399999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 43, 12, 31, 31, 'prince of this world', 'Connection of the Prince of the World', 'Both passages emphasize the role of the ''prince of this world'' in relation to judgment and Jesus. John 14:30 indicates that this figure has no claim on Jesus, while John 12:31 proclaims his impending defeat.', 'theme', 0.44699999999999995, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 49, 6, 12, 12, 'prince of this world', 'Spiritual Warfare and Authority', 'This connection highlights the concept of spiritual conflict. Both passages emphasize the presence of a powerful adversary, referred to as ''the prince of this world'' in John and ''rulers of the darkness of this world'' in Ephesians.', 'theme', 0.43999999999999995, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 47, 4, 4, 4, 'prince of this world', 'Connection of Worldly Influence', 'Both passages emphasize the concept of a ''prince'' or ''god'' of this world who exerts influence over people''s minds. In John 14:30, Jesus refers to the ''prince of this world,'' while 2 Corinthians 4:4 mentions the ''god of this world'' blinding non-believers. This connection highlights the spiritual opposition faced by believers.', 'theme', 0.419, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 30, 49, 2, 2, 2, 'prince of this world', 'Connection of Worldly Influence', 'Both passages emphasize the role of a malevolent force, referred to as the ''prince of this world'' in John and the ''prince of the power of the air'' in Ephesians. This connection highlights the pervasive influence of evil in the world and its impact on humanity.', 'theme', 0.419, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 43, 10, 18, 18, NULL, 'Connection of Commandments and Authority', 'Both passages emphasize the theme of obedience to the Father''s commandment. In John 14:31, Jesus acts in accordance with the command given by the Father, while in John 10:18, He speaks of the authority to lay down His life as a commandment received from the Father.', 'theme', 0.363, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 50, 2, 8, 8, 'even so I do', 'Obedience and Love Connection', 'This connection highlights the theme of obedience in both passages. In John 14:31, Jesus expresses his obedience to the Father''s command, while Philippians 2:8 emphasizes his obedience unto death.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 42, 12, 50, 50, 'as the Father gave me commandment', 'Connection of Obedience and Suffering', 'This connection highlights the theme of obedience to divine command and the accompanying suffering. In John 14:31, Jesus emphasizes His obedience to the Father''s command, while in Luke 12:50, He speaks of the impending baptism, symbolizing His suffering that must be accomplished.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 43, 4, 34, 34, 'the Father gave me commandment', 'Connection of Obedience and Will', 'Both passages emphasize the importance of doing the will of the Father. In John 14:31, Jesus expresses His obedience to the Father''s commandment, while in John 4:34, He states that His purpose is to fulfill the Father''s work.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 58, 5, 7, 8, 'as the Father gave me commandment', 'Obedience and Suffering Connection', 'This connection highlights the theme of obedience in both passages. John 14:31 emphasizes Jesus'' obedience to the Father''s commandment, while Hebrews 5:7-8 discusses how Jesus learned obedience through suffering.', 'theme', 0.34199999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 19, 40, 8, 8, NULL, 'Connection of Divine Will', 'Both passages emphasize the obedience to God''s will. John 14:31 reflects Jesus'' commitment to the Father''s command, while Psalms 40:8 expresses a delight in doing God''s will.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 14, 31, 40, 26, 39, 39, NULL, 'Obedience to the Father''s Will', 'Both passages emphasize the theme of obedience to the Father''s will. In John 14:31, Jesus expresses His commitment to follow the Father''s command, while in Matthew 26:39, He submits to the Father''s will in prayer.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();