INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 13, 36, 43, 16, 17, 17, 'whither I go, thou canst not follow me now', 'Disciples'' Confusion About Jesus'' Departure', 'This connection highlights the disciples'' struggle to understand Jesus'' statements about his departure. Both passages reflect their confusion regarding his going away and the promise of seeing him again.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 44, 20, 24, 24, 'I will lay down my life', 'Commitment to Sacrifice', 'This connection highlights Peter''s initial declaration to lay down his life for Jesus and parallels Paul''s later commitment to not count his life dear in order to fulfill his ministry. Both passages emphasize a willingness to sacrifice personal safety for a greater purpose.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 44, 21, 13, 13, 'lay down my life for thy sake', 'Commitment to Sacrifice', 'Both passages emphasize a willingness to die for Jesus. Peter expresses his readiness to lay down his life, while Paul declares his readiness to die at Jerusalem for the name of the Lord Jesus.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 41, 14, 27, 31, 'I will lay down my life for thy sake', 'Peter''s Loyalty and Denial', 'Both passages emphasize Peter''s declaration of loyalty to Jesus, as he states, ''I will lay down my life for thy sake'' in John and insists he will not deny Jesus in Mark. This connection highlights Peter''s strong commitment contrasted with his eventual denial.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 43, 21, 15, 15, 'I will lay down my life', 'Peter''s Commitment to Jesus', 'This connection highlights Peter''s declaration of loyalty in John 13:37, where he expresses his willingness to lay down his life for Jesus. In John 21:15, Jesus questions Peter''s love, reinforcing the theme of commitment and responsibility in their relationship.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 40, 26, 31, 35, 'I will lay down my life for thy sake', 'Peter''s Loyalty and Denial', 'Both passages emphasize Peter''s declaration of loyalty to Jesus, stating he will not deny Him. This connection highlights the contrast between Peter''s confidence and the prediction of his denial.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 37, 42, 22, 31, 34, 'I will lay down my life for thy sake', 'Peter''s Commitment and Denial', 'Both passages emphasize Peter''s bold declaration of loyalty, as he expresses his willingness to lay down his life and readiness to follow Jesus into danger. However, they also foreshadow his impending denial, highlighting the tension between his confidence and future failure.', 'theme', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 42, 22, 34, 34, 'the cock shall not crow, till thou hast denied me thrice', 'Peter''s Denial Foretold', 'Both passages emphasize Peter''s denial of Jesus, specifically stating that he will deny knowing Him thrice before the cock crows. This connection highlights the prophetic nature of Jesus'' prediction regarding Peter''s actions.', 'prophecy', 0.384, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 40, 26, 34, 34, NULL, 'Denial Prediction Connection', 'Both passages emphasize the prediction of Peter''s denial of Jesus. They specifically mention the timing of the denial in relation to the crowing of the cock.', 'parallel', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 41, 14, 30, 30, NULL, 'Denial Prediction Connection', 'Both passages emphasize the prediction of Peter''s denial of Jesus. They highlight the specific detail that Peter will deny Jesus thrice before the cock crows.', 'parallel', 0.37, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 20, 16, 18, 18, 'lay down thy life for my sake', 'Connection of Pride and Denial', 'This connection highlights the theme of pride leading to downfall. In John 13:38, Peter''s confidence in his loyalty reflects pride, which ultimately leads to his denial of Jesus. Similarly, Proverbs 16:18 warns that pride precedes destruction.', 'theme', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 40, 26, 69, 75, 'thou hast denied me thrice', 'Peter''s Denial Foretold', 'Both passages emphasize Peter''s denial of Jesus and the prophecy of it. The source verse predicts that Peter will deny Jesus thrice before the cock crows, which is fulfilled in the target passage when Peter denies knowing Jesus three times.', 'prophecy', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 42, 22, 56, 62, 'The cock shall not crow, till thou hast denied me thrice.', 'Denial of Peter Foretold', 'This connection highlights the prophecy of Peter''s denial made by Jesus in John 13:38 and its fulfillment in Luke 22:56-62. Both passages emphasize the moment of denial and the crowing of the cock, illustrating the accuracy of Jesus'' prediction.', 'prophecy', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 13, 38, 20, 28, 26, 26, NULL, 'Trust and Denial', 'This connection highlights the theme of trust and wisdom. In John 13:38, Peter''s self-confidence leads to his denial of Jesus, while Proverbs 28:26 warns that trusting in one''s own heart is foolish. Both passages emphasize the importance of wise discernment over self-reliance.', 'theme', 0.293, 'medium', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();