INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 9, 39, 62, 2, 11, 11, 'might see', 'Connection of Sight and Darkness', 'This connection highlights the theme of spiritual blindness and insight. Both passages emphasize the consequences of one''s moral state, where those who are blind or in darkness lack true understanding.', 'theme', 0.34199999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 39, 42, 1, 79, 79, NULL, 'Light and Darkness Connection', 'Both passages emphasize the theme of light illuminating darkness. John 9:39 speaks of bringing sight to the blind, while Luke 1:79 mentions giving light to those in darkness.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 39, 40, 13, 13, 15, 'that they which see not might see', 'Seeing and Understanding', 'Both passages emphasize the contrast between seeing and not seeing, as well as understanding and not understanding. They highlight the spiritual blindness of those who fail to perceive the truth, linking judgment and revelation.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 66, 3, 17, 17, 'Are we blind also?', 'Blindness and Spiritual Awareness', 'This connection highlights the theme of spiritual blindness. Both passages address the condition of being blind, with the Pharisees questioning their own blindness in John, while Revelation describes a state of being blind and unaware of one''s true condition.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 40, 15, 12, 14, 'Are we blind also?', 'Blindness of the Pharisees', 'Both passages emphasize the spiritual blindness of the Pharisees. In John, they question their own blindness, while in Matthew, Jesus describes them as ''blind leaders of the blind.'' This connection highlights their lack of understanding and guidance.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 40, 23, 16, 28, 'Are we blind also?', 'Blindness of the Pharisees', 'Both passages emphasize the spiritual blindness of the Pharisees. In John 9:40, they question their own blindness, while Matthew 23:16-28 condemns them as ''blind guides'' for their misguided teachings.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 42, 11, 39, 54, 'Are we blind also?', 'Pharisees and Spiritual Blindness', 'This connection highlights the theme of spiritual blindness among the Pharisees. In John 9:40, their question about being blind reflects their lack of understanding, which is further emphasized in Luke 11:39-54, where Jesus criticizes their focus on outward appearances while neglecting their inner wickedness.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 43, 7, 47, 52, 'Are we blind also?', 'Pharisees'' Perception of Blindness', 'This connection highlights the Pharisees'' questioning of their understanding and perception of truth. In both passages, the Pharisees express skepticism about belief in Jesus, indicating a theme of spiritual blindness and ignorance of the law.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 43, 9, 34, 34, 'Are we blind also?', 'Blindness and Spiritual Insight', 'Both passages emphasize the theme of spiritual blindness. The Pharisees'' question about being ''blind'' connects to their earlier rejection of the man born blind, highlighting their inability to recognize truth.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 40, 45, 2, 19, 22, 'Are we blind also?', 'Blindness and Spiritual Insight', 'This connection highlights the theme of spiritual blindness and the responsibility of teachers. Both passages address the idea of guiding the blind and the need for self-examination among those who claim to have knowledge.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 23, 5, 21, 21, 'We see; therefore your sin remaineth.', 'Wisdom and Blindness Connection', 'This connection highlights the theme of self-perception and spiritual blindness. Both passages emphasize the danger of being ''wise in their own eyes'' and claiming to ''see,'' which leads to sin remaining.', 'theme', 0.419, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 43, 15, 22, 24, 'ye say, We see; therefore your sin remaineth', 'Connection of Sin and Sight', 'Both passages emphasize the concept of sin being linked to awareness and rejection of truth. In John 9:41, Jesus indicates that acknowledging sight brings accountability for sin, while John 15:22-24 reinforces that His coming exposes their sin, leaving them without excuse.', 'theme', 0.40499999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 42, 18, 14, 14, 'We see; therefore your sin remaineth', 'Humility and Spiritual Insight', 'This connection highlights the theme of humility in recognizing one''s spiritual blindness. Both passages emphasize that those who acknowledge their limitations and do not exalt themselves are justified, while those who claim to see remain in their sin.', 'theme', 0.391, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 62, 1, 8, 10, 'We see; therefore your sin remaineth', 'Sin and Acknowledgment of Truth', 'This connection highlights the theme of acknowledging sin. Both passages emphasize the danger of claiming to be without sin, which leads to self-deception and the absence of truth.', 'theme', 0.391, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 20, 26, 12, 12, 'We see; therefore your sin remaineth', 'Conceit and Spiritual Blindness', 'This connection highlights the theme of self-deception. Both passages emphasize the danger of claiming wisdom or sight while remaining blind to one''s own shortcomings.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 58, 10, 26, 26, 'ye say, We see; therefore your sin remaineth', 'Connection of Sin and Knowledge', 'This connection highlights the relationship between knowledge and accountability in sin. Both passages emphasize that awareness of truth or sight brings responsibility for sin, suggesting that ignorance may mitigate culpability.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 9, 41, 24, 2, 35, 35, NULL, 'Blindness and Sinfulness Connection', 'Both passages emphasize the theme of self-deception regarding sin. In John 9:41, the claim of sight leads to remaining sin, while Jeremiah 2:35 highlights the assertion of innocence despite sin. This connection highlights the danger of claiming righteousness without acknowledgment of wrongdoing.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();