INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 12, 48, 43, 11, 24, 24, 'the last day', 'Resurrection and Judgment Connection', 'This connection highlights the theme of the ''last day'' in both passages. John 12:48 speaks of judgment on that day, while John 11:24 refers to the resurrection occurring at the same time.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 48, 58, 12, 25, 25, 'rejecteth me, and receiveth not my words', 'Judgment and Refusal of Words', 'This connection highlights the theme of rejecting divine communication. Both passages emphasize the consequences of refusing the words spoken, whether by Jesus or from heaven.', 'theme', 0.37, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 43, 14, 10, 10, NULL, 'Connection of Divine Command', 'Both passages emphasize that Jesus speaks not of himself, but conveys the words and works of the Father. This connection highlights the unity between Jesus and the Father in their communication and actions.', 'theme', 0.426, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 43, 8, 26, 26, 'the Father which sent me', 'Connection of Divine Command', 'Both passages emphasize the authority of the Father in Jesus'' words. John 12:49 highlights the commandment given by the Father, while John 8:26 refers to speaking what he has heard from the Father.', 'theme', 0.419, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 43, 5, 30, 30, NULL, 'Connection of Divine Command', 'Both passages emphasize the dependence of Jesus on the Father for guidance and authority. They highlight that Jesus does not act on his own will but follows the commandment given by the Father.', 'theme', 0.412, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 43, 17, 8, 8, 'the Father which sent me', 'Connection of Divine Command', 'This connection highlights the theme of divine communication. Both passages emphasize the transmission of words from the Father to Jesus and then to the disciples.', 'theme', 0.40499999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 5, 18, 18, 18, 'what I should say, and what I should speak', 'Connection of Divine Command', 'Both passages emphasize the theme of divine commandment. John 12:49 speaks of the Father giving a commandment for Jesus to speak, while Deuteronomy 18:18 mentions God putting His words in the mouth of the Prophet.', 'theme', 0.391, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 49, 66, 1, 1, 1, 'the Father which sent me, he gave me a commandment', 'Divine Command and Revelation', 'This connection highlights the theme of divine communication. Both passages emphasize that the messages conveyed are given by God, with Jesus receiving commands from the Father and then revealing them to His servants.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 50, 43, 17, 3, 3, 'life everlasting', 'Connection of Eternal Life', 'Both passages emphasize the concept of life everlasting. John 12:50 speaks of the commandment leading to life everlasting, while John 17:3 defines eternal life as knowing God and Jesus Christ.', 'theme', 0.34199999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 50, 43, 6, 68, 68, 'life everlasting', 'Connection of Eternal Life', 'Both passages emphasize the concept of eternal life. In John 12:50, Jesus speaks of the commandment that leads to life everlasting, while in John 6:68, Peter acknowledges that Jesus has the words of eternal life.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 50, 62, 5, 20, 20, 'life everlasting', 'Connection of Eternal Life', 'Both passages emphasize the concept of eternal life. John 12:50 speaks of the commandment leading to life everlasting, while 1 John 5:20 identifies Jesus Christ as the true God and eternal life.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 50, 54, 1, 16, 16, 'life everlasting', 'Connection of Life Everlasting', 'Both passages emphasize the concept of life everlasting as a central theme. John 12:50 speaks of the commandment leading to life everlasting, while 1 Timothy 1:16 refers to belief in Jesus Christ for life everlasting.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 12, 50, 62, 2, 25, 25, 'life everlasting', 'Connection of Eternal Life', 'Both passages emphasize the concept of eternal life. John 12:50 speaks of life everlasting through obedience to God''s command, while 1 John 2:25 directly mentions the promise of eternal life.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();