INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 8, 56, 48, 3, 7, 9, NULL, 'Connection of Abraham and Faith', 'This connection highlights the significance of Abraham''s faith in relation to the blessings promised to all nations. Both passages emphasize that those who share in Abraham''s faith are considered his children and are blessed.', 'theme', 0.377, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 56, 40, 13, 17, 17, 'my day', 'Desire to See Jesus', 'This connection highlights the theme of longing to witness the fulfillment of God''s promises. Both passages emphasize the anticipation of figures like Abraham and the prophets regarding the coming of Jesus and His teachings.', 'theme', 0.363, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 56, 43, 8, 39, 39, NULL, 'Connection Between Abraham and Jesus', 'Both passages emphasize the relationship between Jesus and Abraham. In John 8:39, Jesus challenges the claim of being Abraham''s children, while in John 8:56, he highlights Abraham''s anticipation of his coming.', 'theme', 0.363, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 56, 42, 10, 24, 24, 'my day', 'Desire to See Jesus', 'This connection highlights the longing of figures like Abraham, prophets, and kings to witness the fulfillment of God''s promises. Both passages emphasize the joy and anticipation surrounding the revelation of Jesus and His ministry.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 56, 60, 1, 10, 12, NULL, 'Connection of Prophetic Revelation', 'This connection highlights the theme of prophetic insight into Christ''s coming. Both passages emphasize the anticipation of salvation and the joy associated with the revelation of Christ''s glory.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 2, 3, 14, 14, 'I am', 'Divine Identity Connection', 'This connection highlights the use of ''I AM'' in both passages, emphasizing the divine identity of Jesus in John 8:58 and God''s self-identification in Exodus 3:14. Both passages assert a timeless existence that transcends human history.', 'keyword', 0.622, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 51, 1, 17, 17, 'Before Abraham was, I am', 'Eternal Nature of Christ', 'This connection highlights the eternal existence of Christ. Both passages emphasize that Jesus exists before all things, linking his preeminence to the concept of being ''before'' Abraham.', 'theme', 0.489, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 43, 17, 5, 5, 'before Abraham was, I am', 'Eternal Existence of Jesus', 'This connection highlights Jesus'' existence before Abraham and before the world. Both passages emphasize His pre-existence and divine nature.', 'theme', 0.475, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 43, 1, 1, 2, 'I am', 'Connection of Divine Existence', 'This connection highlights the eternal nature of Jesus as both ''I am'' and ''the Word.'' Both passages emphasize the pre-existence of Jesus before Abraham and at the beginning of creation.', 'theme', 0.46099999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 23, 44, 6, 6, 'I am', 'Divine Identity Connection', 'This connection highlights the assertion of divine identity in both passages. Jesus'' declaration of ''I am'' parallels the Lord''s self-identification as ''I am the first, and I am the last.''', 'theme', 0.44699999999999995, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 58, 13, 8, 8, 'I am', 'Eternal Nature of Jesus', 'This connection highlights the eternal existence of Jesus. In John 8:58, Jesus asserts His existence before Abraham, while Hebrews 13:8 emphasizes His unchanging nature through time.', 'theme', 0.426, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 58, 66, 1, 8, 8, 'I am', 'Divine Identity and Eternity', 'This connection highlights the eternal nature of Jesus, as both passages affirm His existence before time and His role as the beginning and the ending. The phrase ''I am'' in John 8:58 parallels the declaration of ''I am Alpha and Omega'' in Revelation 1:8, emphasizing His divine identity.', 'theme', 0.426, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 43, 11, 8, 8, NULL, 'Threat of Stoning', 'This connection highlights the ongoing danger Jesus faced from the Jews, as both passages reference attempts to stone him. In John 8:59, the immediate threat is evident, while John 11:8 recalls this danger as the disciples express concern about returning to that location.', 'theme', 0.356, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 43, 10, 30, 33, 'took they up stones to cast at him', 'Reactions to Jesus'' Claims', 'Both passages emphasize the Jews'' violent reaction to Jesus'' claims about his identity. In each instance, they take up stones to stone him, indicating their rejection of his assertions. This connection highlights the escalating tension surrounding Jesus'' declarations of divinity.', 'theme', 0.34199999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 3, 24, 16, 16, NULL, 'Connection of Blasphemy and Punishment', 'Both passages emphasize the act of blasphemy and the severe consequences that follow. In John 8:59, the reaction of the crowd to Jesus suggests they viewed his words as blasphemous, aligning with the punishment outlined in Leviticus 24:16.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 42, 4, 29, 30, NULL, 'Jesus Passing Through Hostile Crowds', 'Both passages emphasize Jesus'' ability to navigate hostile situations unharmed. In each instance, he passes through a crowd intent on violence without being harmed.', 'parallel', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 1, 19, 11, 11, 'hid himself', 'Blindness and Escape', 'This connection highlights the theme of divine intervention in moments of danger. In both passages, individuals are protected from harm—Jesus escapes the stones, while the men at Lot''s door are blinded to prevent their assault.', 'theme', 0.314, 'medium', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 12, 6, 18, 20, 'hid himself', 'Blindness and Sight', 'This connection highlights the theme of blindness and sight in both passages. In John 8:59, Jesus hides himself, paralleling the blindness inflicted on the people in 2 Kings 6:18, followed by the restoration of sight.', 'theme', 0.314, 'medium', 'v1.2', 'gpt-4o-mini'),
(43, 8, 59, 42, 24, 31, 31, NULL, 'Vanishing and Hidden Presence', 'This connection highlights the theme of Jesus'' ability to hide or vanish from sight. In both passages, Jesus is not physically present to those around him, emphasizing a mysterious aspect of his presence.', 'theme', 0.314, 'medium', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();