INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 4, 49, 19, 88, 10, 12, 'ere my child die', 'Connection of Life and Death', 'This connection highlights the themes of life and death. The nobleman''s plea for his child''s life in John 4:49 contrasts with the questions about the dead in Psalms 88:10-12, emphasizing the urgency of life and the silence of death.', 'theme', 0.314, 'medium', 'v1.2', 'gpt-4o-mini'),
(43, 4, 49, 41, 5, 35, 36, 'come down ere my child die', 'Faith in Crisis', 'Both passages emphasize the urgent plea for healing in desperate situations. The nobleman''s request for Jesus to come before his child dies parallels the ruler''s fear upon hearing his daughter is dead, highlighting the theme of faith amidst hopelessness.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 40, 8, 13, 13, 'Go thy way', 'Healing through Faith', 'This connection highlights the theme of healing through faith, as both passages depict Jesus responding to individuals who believe in His word. In each case, the command to ''Go thy way'' signifies the faith of the individuals leading to miraculous healing.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 41, 7, 29, 30, 'Go thy way', 'Healing by Faith', 'Both passages emphasize the theme of healing through faith. In each case, the individuals believe Jesus'' words and find their loved ones healed, demonstrating the power of faith in His authority.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 42, 17, 14, 14, 'Go thy way; thy son liveth', 'Faith and Healing Connection', 'This connection highlights the theme of faith leading to healing. In both passages, individuals act on Jesus'' words and experience miraculous healing as they go on their way.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 45, 4, 20, 21, 'believed the word that Jesus had spoken', 'Faith in God''s Promises', 'This connection highlights the theme of belief in God''s promises. Both passages emphasize the importance of faith in receiving God''s assurance, as seen in the man''s belief in Jesus'' words and Abraham''s unwavering faith in God''s ability to fulfill His promise.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 41, 9, 23, 24, 'believed the word that Jesus had spoken', 'Connection of Belief in Healing', 'Both passages emphasize the importance of belief in the context of healing. In John, the man believes Jesus'' word about his son, while in Mark, the father expresses his belief and seeks help for his unbelief.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 43, 11, 40, 40, 'believed the word that Jesus had spoken', 'Belief and Divine Assurance', 'Both passages emphasize the importance of belief in Jesus'' words. In John 4:50, the man''s belief leads to his son''s healing, while in John 11:40, belief is linked to witnessing God''s glory.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 50, 44, 14, 9, 10, 'believed the word that Jesus had spoken', 'Faith Leading to Healing', 'Both passages emphasize the role of faith in healing. In John 4:50, the man''s belief in Jesus'' word results in his son''s healing, while in Acts 14:9-10, the man''s faith prompts Paul to command him to stand and be healed.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 51, 11, 17, 23, 23, 'Thy son liveth', 'Connection of Life Restoration', 'Both passages emphasize the phrase ''thy son liveth,'' indicating a miraculous restoration of life. This connection highlights the theme of divine intervention in moments of despair.', 'theme', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 51, 43, 4, 50, 50, 'thy son liveth', 'Connection of Healing and Belief', 'Both passages emphasize the phrase ''thy son liveth,'' which signifies the healing of the man''s son and the man''s subsequent belief in Jesus'' words. This connection highlights the relationship between faith and the miraculous outcome.', 'theme', 0.3, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 51, 43, 4, 53, 53, 'Thy son liveth', 'Father''s Belief in Jesus'' Words', 'This connection highlights the moment when the father learns that his son is alive, which directly correlates with Jesus'' earlier proclamation. Both passages emphasize the phrase ''Thy son liveth'' as a pivotal point that leads to the father''s belief.', 'theme', 0.3, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 19, 107, 20, 20, 'Thy son liveth', 'Healing Through God''s Word', 'This connection highlights the theme of healing through the spoken word of Jesus in John 4:53 and God''s word in Psalms 107:20. Both passages emphasize the power of divine communication to bring about healing and deliverance.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 42, 19, 9, 9, 'Thy son liveth', 'Salvation and Belief in Households', 'This connection highlights the theme of belief leading to salvation within households. Both passages emphasize the transformative impact of faith on the entire family unit.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 19, 33, 9, 9, 'Thy son liveth', 'Power of God''s Word', 'This connection highlights the authority of Jesus'' words in John 4:53, where His command results in the healing of the son. Similarly, Psalms 33:9 emphasizes that God''s spoken word brings about immediate action, illustrating the power and reliability of divine commands.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 40, 8, 13, 13, NULL, 'Healing at the Same Hour', 'Both passages emphasize healing occurring at the same hour, demonstrating the power of belief in Jesus'' words. The centurion''s faith leads to his servant''s healing, paralleling the father''s belief resulting in his son''s recovery.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 44, 11, 14, 14, 'and himself believed, and his whole house', 'Salvation of Households', 'Both passages emphasize the belief of a household in connection with salvation. In John 4:53, the father''s belief leads to the life of his son, while Acts 11:14 speaks of words that will save the entire household.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 53, 44, 16, 34, 34, 'believed, and his whole house', 'Belief of Households', 'Both passages emphasize the belief of entire households in response to miraculous events. In John, the father''s belief leads to the faith of his whole house, while in Acts, the jailer''s belief results in rejoicing with his household.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 54, 43, 2, 1, 11, 'this is again the second miracle', 'Miracles of Jesus in Galilee', 'Both passages emphasize Jesus'' miracles in Galilee. The first miracle in Cana of Galilee is identified as the beginning of his signs, leading to belief among his disciples, which is referenced in the second miracle mentioned in John 4:54.', 'theme', 0.307, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 4, 54, 43, 4, 45, 45, NULL, 'Miracles and Reception in Galilee', 'Both passages emphasize Jesus'' arrival in Galilee and the response of the Galileans. The mention of the ''second miracle'' in John 4:54 connects to the Galileans receiving him in John 4:45, highlighting their recognition of his previous works.', 'theme', 0.307, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();