INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 18, 39, 41, 15, 6, 14, 'that I should release unto you one', 'Release of Prisoners', 'Both passages emphasize the custom of releasing a prisoner during Passover. In John, Pilate offers to release ''the King of the Jews,'' while Mark details the choice between Jesus and Barabbas, highlighting the crowd''s preference for Barabbas over Jesus.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 39, 42, 23, 16, 23, 'release unto you one at the passover', 'Release of Prisoners Custom', 'Both passages emphasize the custom of releasing a prisoner at Passover. In John 18:39, Pilate offers to release ''the King of the Jews,'' while Luke 23:16-23 discusses the necessity of releasing one prisoner at the feast, leading to the crowd''s choice of Barabbas over Jesus.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 39, 40, 27, 20, 23, 'release unto you one at the passover', 'Release of Jesus or Barabbas', 'Both passages emphasize the choice presented to the crowd regarding the release of a prisoner during Passover. John 18:39 mentions the custom of releasing one at Passover, while Matthew 27:20-23 illustrates the crowd''s decision to choose Barabbas over Jesus.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 40, 27, 16, 16, 'Barabbas', 'Connection of Barabbas References', 'Both passages emphasize Barabbas as a notable prisoner. John 18:40 identifies him as a robber, while Matthew 27:16 introduces him as a notable prisoner, linking their narratives.', 'parallel', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 40, 27, 26, 26, 'Barabbas was a robber', 'Release of Barabbas', 'Both passages emphasize the release of Barabbas, a robber, in contrast to Jesus. This connection highlights the choice made by the crowd to free Barabbas instead of Jesus, leading to Jesus'' crucifixion.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 41, 15, 7, 7, 'Barabbas was a robber', 'Connection of Barabbas in Gospels', 'Both passages emphasize Barabbas as a criminal. John identifies him as a robber, while Mark describes him as involved in murder during an insurrection. This connection highlights the nature of Barabbas as a significant figure in the narrative of Jesus'' trial.', 'parallel', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 41, 15, 15, 15, 'Barabbas', 'Connection of Barabbas'' Release', 'Both passages emphasize the release of Barabbas, highlighting the choice made by the crowd to free him instead of Jesus. This connection illustrates the pivotal moment in the trial of Jesus and the people''s preference for Barabbas, a robber.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 42, 23, 18, 19, 'Not this man, but Barabbas', 'Connection of Barabbas in Trials', 'Both passages emphasize the crowd''s demand for Barabbas over Jesus. They highlight the choice made by the people, linking Barabbas to criminal behavior.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 42, 23, 25, 25, 'Not this man, but Barabbas', 'Connection of Barabbas and Jesus', 'Both passages emphasize the choice between Barabbas and Jesus. In John, the crowd demands Barabbas, while Luke describes him as released, highlighting the contrast between the two figures.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 18, 40, 44, 3, 13, 14, NULL, 'Denial of Jesus and Barabbas', 'This connection highlights the theme of choosing a criminal over Jesus. Both passages emphasize the crowd''s desire for Barabbas, a murderer, instead of the Holy One, Jesus.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();