INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(43, 5, 44, 9, 2, 30, 30, 'honour that cometh from God only', 'Honor and Esteem in God', 'Both passages emphasize the theme of honor, contrasting human honor with divine honor. John 5:44 speaks of seeking honor from God, while 1 Samuel 2:30 states that God will honor those who honor Him.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 44, 60, 1, 7, 7, 'honour that cometh from God only', 'Honor from God vs. Honor from Others', 'This connection highlights the contrast between seeking honor from others and the honor that comes from God. Both passages emphasize the importance of divine approval over human recognition, particularly in the context of faith and trials.', 'theme', 0.349, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 45, 3, 19, 20, 'in whom ye trust', 'Connection of Law and Accusation', 'This connection highlights the role of the law in revealing guilt. Both passages emphasize that reliance on the law leads to condemnation rather than justification.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 48, 3, 10, 10, 'Moses, in whom ye trust', 'Connection Between Law and Accusation', 'This connection highlights the role of the law as a source of accusation. In John, Moses is presented as the accuser, while Galatians emphasizes the curse for failing to uphold the law.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 47, 3, 7, 11, 'Moses, in whom ye trust', 'Moses and Glory Connection', 'This connection highlights the role of Moses as an accuser in John 5:45 and contrasts it with the glory associated with his ministry in 2 Corinthians 3:7-11. Both passages emphasize the significance of Moses in relation to the law and its implications for righteousness and condemnation.', 'theme', 0.32799999999999996, 'medium', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 43, 9, 28, 29, 'Moses, in whom ye trust', 'Connection Between Moses and Accusation', 'Both passages emphasize the authority of Moses in the context of belief. In John 5:45, Jesus indicates that Moses serves as an accuser, while in John 9:28-29, the Pharisees assert their allegiance to Moses, highlighting their trust in him over Jesus.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 45, 2, 12, 12, 'accuseth you, even Moses', 'Judgment and Law Connection', 'This connection highlights the theme of judgment based on the law. In John 5:45, Moses is presented as an accuser, while Romans 2:12 discusses judgment for those who have sinned in relation to the law.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 40, 19, 7, 8, 'Moses, in whom ye trust', 'Moses and Hardness of Hearts', 'This connection highlights the role of Moses as an authority in both passages. In John, Moses is presented as an accuser, while in Matthew, his allowance for divorce is attributed to the hardness of hearts, suggesting a complex relationship with the law he represents.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 45, 43, 7, 19, 19, 'Moses, in whom ye trust', 'Moses and the Law Connection', 'This connection highlights the role of Moses as a figure of authority regarding the law. Both passages emphasize the failure of the people to uphold the law given by Moses, linking their trust in him to their actions against Jesus.', 'theme', 0.314, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 5, 18, 15, 15, 'he wrote of me', 'Connection Between Moses and the Prophet', 'This connection highlights the expectation of a Prophet like Moses, as indicated in Deuteronomy. Jesus claims that Moses wrote of him, suggesting that he fulfills this prophetic role.', 'prophecy', 0.7969999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 43, 1, 45, 45, NULL, 'Connection of Moses and Jesus', 'Both passages emphasize the connection between Moses and Jesus, indicating that Moses wrote about Him. John 1:45 explicitly states that Jesus is the one of whom Moses in the law wrote.', 'theme', 0.566, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 42, 24, 27, 27, 'for he wrote of me', 'Connection of Moses and Scriptures', 'Both passages emphasize the significance of Moses in relation to Jesus. John 5:46 states that Moses wrote of Jesus, while Luke 24:27 indicates that Jesus expounded on the scriptures starting with Moses.', 'theme', 0.517, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 4, 24, 17, 18, 'he wrote of me', 'Connection of Prophecy and Fulfillment', 'This connection highlights the prophetic nature of Numbers 24:17-18, which anticipates a future leader from Israel, referred to as a ''Star'' and ''Sceptre.'' John 5:46 emphasizes that Moses wrote of Jesus, indicating that Jesus fulfills this prophecy as the awaited figure.', 'prophecy', 0.482, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 1, 49, 10, 10, 'for he wrote of me', 'Connection of Prophecy and Belief', 'This connection highlights the belief in Moses'' writings as a precursor to recognizing Shiloh, the figure referenced in Genesis. Both passages emphasize the expectation of a leader, with John asserting that Moses wrote of Jesus, linking him to the prophecy of Judah''s sceptre.', 'prophecy', 0.46799999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 44, 26, 22, 22, NULL, 'Connection Between Moses and Prophets', 'This connection highlights the continuity between Moses'' writings and the prophetic message. Both passages emphasize the importance of believing in the words of Moses as they relate to Jesus and the prophets.', 'theme', 0.46799999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 46, 1, 22, 18, 18, NULL, 'Connection of Blessing Through Obedience', 'This connection highlights the theme of blessing through obedience. In Genesis, the promise of blessing to all nations is linked to Abraham''s obedience, while in John, believing in Moses is tied to recognizing Jesus as the fulfillment of that promise.', 'theme', 0.43999999999999995, 'medium', 'v1.2', 'gpt-4o-mini'),
(43, 5, 47, 42, 16, 31, 31, 'believe not his writings', 'Faith in Scripture''s Authority', 'This connection highlights the importance of believing in the writings of Moses and the prophets as a prerequisite for faith in Jesus'' words. Both passages emphasize that if one does not accept the foundational scriptures, they will not be persuaded by miraculous signs or teachings.', 'theme', 0.34199999999999997, 'high', 'v1.2', 'gpt-4o-mini'),
(43, 5, 47, 42, 16, 29, 29, 'believe my words', 'Connection of Belief and Scripture', 'This connection highlights the importance of believing in the writings of Moses and the prophets as a prerequisite for understanding Jesus'' words. Both passages emphasize the necessity of scripture for faith.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();