INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, prompt_version, model)
VALUES
(43, 1, 49, 43, 1, 34, 34, 'Son of God', 'Recognition of Jesus'' Divinity', 'Both passages emphasize Jesus'' identity as the Son of God, highlighting the early recognition of His divine nature. Nathanael''s declaration in John 1:49 follows John the Baptist''s testimony in John 1:34, reinforcing the theme that Jesus'' divine sonship is central to His mission and identity. This connection encourages readers to reflect on the significance of recognizing Jesus as the Messiah.', 'theme', 0.33499999999999996, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 43, 20, 29, 29, 'greater things than these', 'Faith Beyond Sight', 'Both passages emphasize the theme of faith in the unseen. In John 1:50, Jesus hints that greater revelations await those who believe, while John 20:29 highlights the blessedness of those who believe without direct evidence. This connection underscores the call to faith that transcends physical proof, inviting believers to trust in the divine even when not witnessing it firsthand.', 'theme', 0.34199999999999997, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 43, 11, 40, 40, 'if thou wouldest believe', 'Belief and Divine Revelation', 'Both passages emphasize the theme of belief leading to the revelation of God''s glory. In John 1:50, Jesus indicates that true faith opens the door to witnessing even greater divine acts, while in John 11:40, He reiterates that belief is essential to seeing God''s glory revealed through miraculous works. This connection highlights the importance of faith as a prerequisite for experiencing God''s presence and power in our lives.', 'theme', 0.33499999999999996, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 42, 1, 45, 45, 'believe/believed', 'Belief and Divine Fulfillment', 'Both passages highlight the theme of belief in God''s promises leading to the manifestation of greater things. In John, Jesus emphasizes that belief opens the door to experiencing God''s greater works, while in Luke, the blessing of belief is affirmed through the fulfillment of divine promises. This connection underscores the transformative power of faith in witnessing God''s actions in one''s life.', 'theme', 0.321, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 40, 25, 29, 29, 'greater things than these', 'Faith and Spiritual Abundance', 'Both passages emphasize the principle that faith and spiritual insight lead to greater blessings and understanding. In John, Jesus indicates that belief will open the door to even greater revelations, while in Matthew, it highlights that those who embrace and utilize their gifts will receive more. Together, they illustrate the idea that spiritual growth is directly linked to one''s faith and responsiveness to divine truths.', 'theme', 0.314, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 42, 7, 9, 9, 'greater things than these', 'Faith and Recognition of Jesus', 'Both passages highlight the theme of faith in Jesus'' authority and power. In John, the promise of witnessing greater things emphasizes the potential for deeper faith, while in Luke, Jesus commends the centurion''s exceptional faith, illustrating that true belief transcends nationality and prior knowledge of Jesus. Together, they reveal how faith can lead to profound spiritual understanding and miracles.', 'theme', 0.3, 'v1.0', 'gpt-4o-mini'),
(43, 1, 50, 40, 13, 12, 12, 'greater things than these', 'Abundance of Faith and Revelation', 'Both passages highlight the idea that those who show faith and understanding will receive even greater insights and blessings from God. In John, Jesus promises Nathanael that he will witness even greater revelations, while in Matthew, the principle emphasizes that those who possess understanding will have more given to them. This connection encourages believers to seek deeper faith, as it leads to greater spiritual abundance.', 'theme', 0.3, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 1, 28, 12, 12, 'angels ascending and descending', 'Angels and Access to Heaven', 'Both passages describe a connection between heaven and earth involving angels, highlighting a divine means of communication. In Genesis, Jacob''s dream of a ladder symbolizes God''s promise and presence, while in John, Jesus identifies himself as the fulfillment of that connection, serving as the mediator between humanity and the divine. This deepens our understanding of Jesus as the ultimate link to heaven.', 'typology', 0.594, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 44, 7, 56, 56, 'heavens opened', 'Heavens Opened and Christ''s Authority', 'Both passages emphasize the opening of heaven and the divine revelation of Jesus'' authority. In John, Jesus speaks of angels ascending and descending upon Him, indicating His role as a mediator, while in Acts, Stephen sees Jesus standing at God''s right hand, affirming His exalted position. This connection highlights the continuity of Christ''s divine nature and authority from His earthly ministry to His heavenly reign.', 'theme', 0.426, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 41, 1, 10, 10, 'heavens opened', 'Angels and the Spirit''s Descent', 'Both passages depict a revelation of the divine, with John foreshadowing the opening of heaven and angels'' activity around Jesus, while Mark describes the actual opening of the heavens and the Spirit''s descent at Jesus'' baptism. This connection emphasizes Jesus'' role as the mediator between heaven and earth, highlighting his divine authority and mission. Together, these moments illustrate the continuity of divine revelation and the inauguration of Jesus'' ministry.', 'theme', 0.391, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 42, 22, 43, 43, 'angels of God ascending and descending', 'Angels and Divine Support', 'Both passages highlight the role of angels in relation to Jesus, illustrating a deeper connection between heaven and earth. In John, angels are depicted as ministering to the Son of Man, while in Luke, an angel specifically strengthens Him during His time of distress. This connection underscores the ongoing divine support Jesus receives as He fulfills His mission.', 'theme', 0.391, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 40, 16, 27, 28, 'angels of God ascending and descending', 'Heavenly Realms and the Son of Man', 'Both passages emphasize the role of the Son of Man in relation to heavenly authority and divine revelation. John describes angels ascending and descending upon Jesus, indicating his connection to God''s presence, while Matthew speaks of Jesus coming in glory with angels, highlighting his authority to judge and reward. This connection reveals that Jesus embodies the intersection between heaven and earth, fulfilling the role of mediator and king.', 'theme', 0.384, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 42, 2, 13, 13, 'angels of God ascending and descending', 'Angelic Announcement and Revelation', 'Both passages highlight the role of angels in revealing God''s presence and purpose. In John, the angels ascend and descend upon Jesus, indicating His divine connection to heaven, while in Luke, the heavenly host announces the birth of Christ, celebrating His significance. This connection emphasizes Jesus as the bridge between heaven and earth, fulfilling God''s plan of salvation.', 'theme', 0.377, 'v1.0', 'gpt-4o-mini'),
(43, 1, 51, 44, 10, 11, 11, 'heaven opened', 'Heaven Opened and Divine Revelation', 'Both passages depict the opening of heaven, symbolizing divine revelation and the connection between God and humanity. In John, this event foreshadows the role of Jesus as the mediator between heaven and earth, while in Acts, it illustrates God’s inclusive vision for all people through the sheet representing Gentiles. Together, they highlight the ongoing unfolding of God''s plan through Christ and the early church.', 'theme', 0.377, 'v1.0', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, updated_at = now();