INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(42, 24, 51, 58, 4, 14, 14, 'carried up into heaven', 'Ascension of Jesus', 'This connection highlights the theme of Jesus'' ascension into heaven. Both passages emphasize that Jesus has ''passed into the heavens,'' affirming his exalted position.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 40, 28, 9, 9, 'worshipped him', 'Worship and Joy After Resurrection', 'Both passages emphasize the act of worship following encounters with Jesus after his resurrection. In Luke, the disciples return with ''great joy'' after worshipping him, while in Matthew, they worship him upon meeting him, indicating a shared theme of reverence and joy.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 19, 30, 11, 11, 'great joy', 'Joy and Gladness in Worship', 'This connection highlights the theme of transformation from sorrow to joy. Both passages emphasize a shift from mourning or sadness to gladness and worship.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 43, 16, 22, 22, 'great joy', 'Joy in Worship and Reunion', 'Both passages emphasize the theme of joy following a significant encounter with Jesus. In Luke, the disciples return with ''great joy'' after worshipping Him, while in John, Jesus promises that their sorrow will turn to joy when they see Him again.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 43, 20, 28, 28, 'worshipped him', 'Worship and Divine Recognition', 'This connection highlights the theme of worship and recognition of Jesus'' divine nature. In both passages, the act of worship is emphasized, with the disciples worshipping Him in Luke and Thomas declaring Him as ''My Lord and my God'' in John.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 60, 1, 8, 8, 'great joy', 'Joy in Belief and Worship', 'Both passages emphasize the theme of joy associated with faith and worship. In Luke, the disciples return with ''great joy'' after worshipping, while in 1 Peter, believers rejoice with ''joy unspeakable'' despite not seeing Christ.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 52, 40, 28, 17, 17, 'worshipped him', 'Worship and Doubt After Resurrection', 'Both passages emphasize the act of worship towards Jesus following his resurrection. While Luke highlights the joy in worship, Matthew notes the presence of doubt among some disciples.', 'theme', 0.321, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 53, 41, 16, 20, 20, 'praising and blessing God', 'Post-Resurrection Activities', 'This connection highlights the activities of the disciples after the resurrection. Both passages emphasize the continuous engagement in worship and the proclamation of God''s message.', 'theme', 0.33499999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 53, 40, 28, 20, 20, 'praising and blessing God', 'Praising God and His Presence', 'Both passages emphasize the importance of God''s presence. In Luke, the disciples are found praising God in the temple, while in Matthew, Jesus assures His continual presence with His followers.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 53, 44, 2, 46, 47, NULL, 'Praising God in Community', 'Both passages emphasize the act of praising God within a communal setting. The continuity of worship in the temple is highlighted in both verses, showing a shared devotion among the early followers.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 53, 44, 5, 41, 42, 'continually in the temple', 'Continual Praise in the Temple', 'Both passages emphasize the theme of being in the temple and praising God. In Luke, the followers are ''continually in the temple, praising and blessing God,'' while in Acts, they are also ''daily in the temple'' teaching and preaching.', 'theme', 0.32799999999999996, 'high', 'v1.2', 'gpt-4o-mini'),
(42, 24, 53, 66, 22, 21, 21, 'praising and blessing God', 'Praise and Grace Connection', 'This connection highlights the theme of worship and blessing in both passages. The continual praising in Luke parallels the grace expressed in Revelation, emphasizing a consistent devotion to God.', 'theme', 0.307, 'medium', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();