INSERT INTO crossref_explanations (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, anchor_phrase, title, content, connection_type, weight, confidence, prompt_version, model)
VALUES
(40, 28, 19, 41, 16, 15, 16, 'Go ye therefore, and teach all nations', 'Commission to Preach and Baptize', 'Both passages emphasize the command to go and teach all nations, highlighting the importance of preaching the gospel and baptizing believers. They share a common theme of spreading the message of salvation through belief and baptism.', 'theme', 1.0, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 44, 2, 38, 39, 'baptizing them in the name', 'Baptism and the Holy Spirit', 'Both passages emphasize the act of baptism and the reception of the Holy Spirit. Matthew 28:19 mentions baptizing in the name of the Father, Son, and Holy Ghost, while Acts 2:38 specifies baptism in the name of Jesus Christ and the gift of the Holy Ghost.', 'theme', 1.0, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 44, 1, 8, 8, 'teach all nations', 'Commission to Witness', 'Both passages emphasize the call to spread the message of Jesus to all nations. Matthew 28:19 instructs to teach and baptize, while Acts 1:8 highlights being witnesses to the ends of the earth.', 'theme', 0.8739999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 42, 24, 47, 48, 'all nations', 'Commission to All Nations', 'Both passages emphasize the mission to teach and preach among all nations. Matthew focuses on baptizing in the name of the Father, Son, and Holy Ghost, while Luke highlights preaching repentance and remission of sins in His name.', 'theme', 0.7899999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 23, 49, 6, 6, 'teach all nations', 'Connection of Salvation to All Nations', 'Both passages emphasize the mission to reach all nations and Gentiles with God''s salvation. Matthew 28:19''s call to teach all nations aligns with Isaiah 49:6''s declaration of being a light to the Gentiles.', 'theme', 0.6779999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 48, 3, 27, 27, 'baptizing them in the name of', 'Baptism and Identity in Christ', 'This connection highlights the act of baptism as a means of entering into a relationship with Christ. Both passages emphasize the significance of baptism in the believer''s identity, linking it to the Father, Son, and Holy Spirit.', 'theme', 0.6639999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 19, 45, 6, 3, 4, 'baptizing them in the name of the Father, and of the Son, and of the Holy Ghost', 'Baptism and New Life Connection', 'This connection highlights the significance of baptism in both passages. Matthew emphasizes baptizing in the name of the Father, Son, and Holy Ghost, while Romans explains that baptism into Jesus Christ signifies a participation in his death and resurrection, leading to newness of life.', 'theme', 0.587, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 23, 41, 10, 10, 'I am with you alway', 'Presence of God in Both Passages', 'Both passages emphasize God''s promise of presence and support. Matthew 28:20 states, ''I am with you alway,'' while Isaiah 41:10 reassures, ''I am with thee.'' This connection highlights the theme of divine companionship.', 'theme', 0.8459999999999999, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 6, 1, 5, 5, 'I am with you alway', 'Presence of God Assurance', 'Both passages emphasize God''s promise of presence and support. Matthew 28:20 assures believers of Jesus'' continual presence, while Joshua 1:5 reaffirms God''s commitment to be with Joshua as He was with Moses.', 'theme', 0.671, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 44, 18, 9, 10, 'I am with you alway', 'Presence of God in Ministry', 'Both passages emphasize God''s promise of presence. In Matthew, Jesus assures His continual presence, while in Acts, the Lord reassures Paul of His presence and protection in ministry.', 'theme', 0.629, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 43, 14, 18, 23, 'I am with you alway', 'Presence and Commandment Connection', 'Both passages emphasize the importance of keeping commandments and the promise of Jesus'' presence. Matthew 28:20 assures believers of Jesus'' continual presence, while John 14:18-23 speaks of Jesus manifesting himself to those who love him by keeping his words.', 'theme', 0.573, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 19, 46, 7, 7, 'I am with you alway', 'Presence of God', 'Both passages emphasize God''s continual presence with His people. Matthew 28:20 assures believers of Christ''s presence ''even unto the end of the world,'' while Psalms 46:7 declares, ''The Lord of hosts is with us.''', 'theme', 0.496, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 1, 39, 2, 3, 'I am with you alway', 'Presence of the Lord', 'Both passages emphasize the presence of the Lord with His followers. In Matthew, Jesus assures His disciples of His continual presence, while in Genesis, Joseph experiences the Lord''s presence, leading to his prosperity.', 'theme', 0.475, 'high', 'v1.2', 'gpt-4o-mini'),
(40, 28, 20, 62, 2, 3, 4, NULL, 'Connection of Commandments and Presence', 'Both passages emphasize the importance of keeping commandments as a sign of knowing Christ. Matthew highlights the command to observe all things, while 1 John asserts that knowing Him is contingent upon keeping His commandments.', 'theme', 0.475, 'high', 'v1.2', 'gpt-4o-mini')
ON CONFLICT (source_book_id, source_chapter, source_verse, target_book_id, target_chapter, target_verse_start, target_verse_end, connection_type) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, anchor_phrase = EXCLUDED.anchor_phrase, weight = EXCLUDED.weight, confidence = EXCLUDED.confidence, updated_at = now();